version: '3.2'
services:
  mysqldb:
    image: mysql:5.7
    container_name: inm-db
    restart: unless-stopped
    env_file:
      - ".env"
    ports:
      - "3306:3306"
    volumes:
      - "./storage/database/mysql:/var/lib/mysql"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  php-fpm:
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    build: docker/php
    container_name: inm-php
    restart: unless-stopped
    volumes:
      - "./docker/php/php.ini:/usr/local/etc/php/php.ini"
      - "./:/var/www/html"
    depends_on:
      - mysqldb
    working_dir: /var/www/html
    environment:
      TIMEZONE: ${TIMEZONE}
      MEMORY_LIMIT: ${MEMORY_LIMIT}

  server:
    image: nginx:latest
    hostname: inm
    ports:
      - "9102:80"
    volumes:
      - "./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf"
      - "./:/var/www/html"
      - "./storage/logs/nginx/:/var/log/nginx"
    depends_on:
      - php-fpm
    restart: unless-stopped
    working_dir: /var/www/html


